version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: Contenedor_Mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MIA2024

  api:
    build: ./backend
    container_name: mia-api
    restart: always
    ports:
      - 3000:3000

  frontend:
    build: ./frontend
    container_name: mia-frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
